ROOMS = [
    {
        "id": "R001",
        "naam": "Standaard Tweepersoonskamer",
        "type": "standard",
        "prijs_per_nacht": 89,
        "locatie": "Den Haag Centrum",
        "capaciteit": 2,
        "ontbijt": False,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Comfortabele tweepersoonskamer met modern interieur in het hartje van Den Haag. Gratis wifi, flatscreen tv en eigen badkamer. Ideaal voor een stedentrip.",
    },
    {
        "id": "R002",
        "naam": "Budget Eenpersoonskamer",
        "type": "standard",
        "prijs_per_nacht": 65,
        "locatie": "Den Haag Centrum",
        "capaciteit": 1,
        "ontbijt": False,
        "parkeren": False,
        "huisdieren": False,
        "beschrijving": "Sfeervolle eenpersoonskamer in een boetiekhotel nabij het centrum. Compact maar volledig ingericht, ideaal voor de zakenreiziger die een comfortabele nacht zoekt.",
    },
    {
        "id": "R003",
        "naam": "Standaard Kamer met Ontbijt",
        "type": "standard",
        "prijs_per_nacht": 105,
        "locatie": "Den Haag Scheveningen",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Lichte tweepersoonskamer met prachtig uitzicht op de duinen van Scheveningen. Inclusief uitgebreid ontbijt, gratis parkeren en wandelafstand van het strand.",
    },
    {
        "id": "R004",
        "naam": "Deluxe Zeezichtkamer",
        "type": "deluxe",
        "prijs_per_nacht": 155,
        "locatie": "Den Haag Scheveningen",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Ruime deluxe kamer met panoramisch uitzicht op de Noordzee. Luxe badkamer met ligbad, koelkast met minibar, inclusief uitgebreid ontbijt en privéparkeerplaats.",
    },
    {
        "id": "R005",
        "naam": "Deluxe Tweepersoonskamer",
        "type": "deluxe",
        "prijs_per_nacht": 130,
        "locatie": "Amsterdam Centrum",
        "capaciteit": 2,
        "ontbijt": False,
        "parkeren": False,
        "huisdieren": False,
        "beschrijving": "Elegante kamer in een historisch grachtenpand in Amsterdam. Houten balken, originele gevelstenen en een moderne badkamer met regendouche. Op loopafstand van de Rijksmuseum.",
    },
    {
        "id": "R006",
        "naam": "Deluxe Kamer met Balkon",
        "type": "deluxe",
        "prijs_per_nacht": 145,
        "locatie": "Rotterdam Centrum",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": True,
        "beschrijving": "Moderne deluxe kamer met privébalkon met uitzicht op de Maas. Geschikt voor huisdieren, inclusief ontbijt en parkeerplaats in de parkeergarage.",
    },
    {
        "id": "R007",
        "naam": "Junior Suite",
        "type": "suite",
        "prijs_per_nacht": 215,
        "locatie": "Den Haag Centrum",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Ruime junior suite met aparte zithoek en een groot tweepersoonsbed. Inclusief gratis ontbijt, parkeren en toegang tot de wellness. Perfect voor een romantisch weekendje weg.",
    },
    {
        "id": "R008",
        "naam": "Penthouse Suite",
        "type": "suite",
        "prijs_per_nacht": 345,
        "locatie": "Amsterdam Centrum",
        "capaciteit": 3,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Exclusieve penthouse suite met terras en 360-graden uitzicht over Amsterdam. Luxe woonkamer, kitchenette en marmeren badkamer. Butler service op aanvraag.",
    },
    {
        "id": "R009",
        "naam": "Suite met Jacuzzi",
        "type": "suite",
        "prijs_per_nacht": 265,
        "locatie": "Rotterdam Centrum",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Romantische suite met privé-jacuzzi en panoramisch uitzicht over Rotterdam. Champagne bij aankomst, kingsize bed en inclusief uitgebreid ontbijt op de kamer.",
    },
    {
        "id": "R010",
        "naam": "Gezins Vierpersoonskamer",
        "type": "family",
        "prijs_per_nacht": 139,
        "locatie": "Den Haag Scheveningen",
        "capaciteit": 4,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Grote familiekamer op 5 minuten van het strand van Scheveningen. Twee aparte slaapzones, bad en douche, kinderbedjes beschikbaar. Inclusief ontbijt en parkeren.",
    },
    {
        "id": "R011",
        "naam": "Gezinsappartement",
        "type": "family",
        "prijs_per_nacht": 175,
        "locatie": "Amsterdam West",
        "capaciteit": 5,
        "ontbijt": False,
        "parkeren": True,
        "huisdieren": True,
        "beschrijving": "Volledig ingerichte appartement voor grote gezinnen of groepen. Eigen keuken, woonkamer, twee slaapkamers en twee badkamers. Huisdieren welkom, privéparkeerplaats aanwezig.",
    },
    {
        "id": "R012",
        "naam": "Gezins Driepersoonskamer",
        "type": "family",
        "prijs_per_nacht": 119,
        "locatie": "Utrecht Centrum",
        "capaciteit": 3,
        "ontbijt": True,
        "parkeren": False,
        "huisdieren": False,
        "beschrijving": "Ruime driepersoonskamer vlakbij het centrum van Utrecht. Extra stapelbed aanwezig, speelhoek voor kinderen en inclusief uitgebreid familieonbijt.",
    },
    {
        "id": "R013",
        "naam": "Business Kamer",
        "type": "business",
        "prijs_per_nacht": 149,
        "locatie": "Den Haag Centrum",
        "capaciteit": 1,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Professioneel ingerichte zakenreizigerskamer met groot bureau, ergonomische stoel, snelle wifi en 24-uurs roomservice. Inclusief ontbijt en parkeerplaats nabij het Centraal Station.",
    },
    {
        "id": "R014",
        "naam": "Business Suite",
        "type": "business",
        "prijs_per_nacht": 195,
        "locatie": "Amsterdam Zuidas",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Stijlvolle business suite op de Zuidas, nabij alle grote kantoorgebouwen. Inclusief een vergaderruimte voor 4 personen, snelle wifi, volledig ontbijt en valet parking.",
    },
    {
        "id": "R015",
        "naam": "Business Tweepersoonskamer",
        "type": "business",
        "prijs_per_nacht": 162,
        "locatie": "Rotterdam Centrum",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Moderne business kamer vlakbij het treinstation van Rotterdam. Twee werkplekken, directe aansluiting op alle vormen van openbaar vervoer, inclusief ontbijt en parkeergarage.",
    },
    {
        "id": "R016",
        "naam": "Romantische Kamer",
        "type": "romantisch",
        "prijs_per_nacht": 179,
        "locatie": "Den Haag Scheveningen",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": True,
        "huisdieren": False,
        "beschrijving": "Intiem ingerichte kamer met rozenblaadjes bij aankomst, champagne, uitzicht op de zee en een knusse open haard. Perfect voor een romantisch weekend aan de kust.",
    },
    {
        "id": "R017",
        "naam": "Boetiek Kamer met Hofje",
        "type": "romantisch",
        "prijs_per_nacht": 134,
        "locatie": "Leiden Centrum",
        "capaciteit": 2,
        "ontbijt": True,
        "parkeren": False,
        "huisdieren": False,
        "beschrijving": "Charmante kamer in een historisch pand met uitzicht op een rustig Leids hofje. Handgemaakte meubels, biologisch ontbijt en op loopafstand van de grachten en musea.",
    },
    {
        "id": "R018",
        "naam": "Huisdierenvriendelijke Kamer",
        "type": "standard",
        "prijs_per_nacht": 95,
        "locatie": "Den Haag Ypenburg",
        "capaciteit": 2,
        "ontbijt": False,
        "parkeren": True,
        "huisdieren": True,
        "beschrijving": "Speciaal ingerichte kamer voor reizigers met huisdieren. Eigen ingang, afwasbare vloer, dierenbenodigdheden op aanvraag en direct aan een groot park. Gratis parkeren.",
    },
]
